//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCopy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoCopy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connections.
        /// </summary>
        internal static string ini_connections {
            get {
                return ResourceManager.GetString("ini_connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my_winform_demo_connection_string.
        /// </summary>
        internal static string ini_connections_mysql {
            get {
                return ResourceManager.GetString("ini_connections_mysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto_copy.ini.
        /// </summary>
        internal static string ini_file_name {
            get {
                return ResourceManager.GetString("ini_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paths.
        /// </summary>
        internal static string ini_paths {
            get {
                return ResourceManager.GetString("ini_paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp_path.
        /// </summary>
        internal static string ini_paths_ftp {
            get {
                return ResourceManager.GetString("ini_paths_ftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local_path.
        /// </summary>
        internal static string ini_paths_local {
            get {
                return ResourceManager.GetString("ini_paths_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string ini_users {
            get {
                return ResourceManager.GetString("ini_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp_password.
        /// </summary>
        internal static string ini_users_ftp_pw {
            get {
                return ResourceManager.GetString("ini_users_ftp_pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp_user.
        /// </summary>
        internal static string ini_users_ftp_user {
            get {
                return ResourceManager.GetString("ini_users_ftp_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_sync_time.txt.
        /// </summary>
        internal static string last_sync_record_file_name {
            get {
                return ResourceManager.GetString("last_sync_record_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.lock.
        /// </summary>
        internal static string lock_file_name {
            get {
                return ResourceManager.GetString("lock_file_name", resourceCulture);
            }
        }
    }
}
